[package]
name = "actix-svelte-template"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
tokio = { version = "1.40.0", features = ["time", "rt", "macros"] }
